In [1]:
import cv2
img = cv2.imread('images/employee.png')
classnames = [] # ليست او array
classfile  = 'files/thing.names'

with open(classfile, 'rt') as f :
    classnames = f.read().rstrip('\n').split('\n')
#print(classnames)
p = 'files/frozen_inference_graph.pb'
v = 'files/ssd_mobilenet_v3_large_coco_2020_01_14.pbtxt'

net = cv2.dnn_DetectionModel(p,v) # الكشف والفحص
net.setInputSize(320,230)         # العرض والارتفاع
net.setInputScale(1.0/127.5)      # القياس
net.setInputMean((127.5,127.5,127.5))
net.setInputSwapRB(True)          # نظام الالوان

classIds ,confs , bbox = net.detect(img, confThreshold=0.5)
#print(classIds,bbox)
for classId , confidence , box in zip(classIds.flatten(),confs.flatten(),bbox):
    cv2.rectangle(img,box,color=(0,255,0),thickness=3)
    cv2.putText(img,classnames[classId-1],
                (box[0]+10,box[1]+20),
                cv2.FONT_HERSHEY_COMPLEX,1,(0,0,255),thickness=2)

cv2.imshow('Rakwan', img)
cv2.waitKey(0)

FileNotFoundError: [Errno 2] No such file or directory: 'files/thing.names'

In [62]:
#جاهز للتعرف باللغه الانجليزيه

import cv2

####### From Image #######
def ImgFile():
    img = cv2.imread(' person.png')

    classNames = []
    classFile = 'coco.arabic.names'

    with open(classFile, 'rt') as f:
        classNames = f.read().rstrip('\n').split('\n')

    configPath = 'ssd_mobilenet_v3_large_coco_2020_01_14.pbtxt'
    weightpath = 'frozen_inference_graph.pb'

    net = cv2.dnn.DetectionModel(weightpath, configPath)
    net.setInputSize(320 , 230)
    net.setInputScale(1.0 / 127.5)
    net.setInputMean((127.5, 127.5, 127.5))
    net.setInputSwapRB(True)

    classIds, confs, bbox = net.detect(img, confThreshold=0.1)
    print(classIds, bbox)

    for classId, confidence, box in zip(classIds.flatten(), confs.flatten(), bbox):
        cv2.rectangle(img, box, color=(0, 255, 0), thickness=2)
        cv2.putText(img, classNames[classId-1], (box[0] + 10, box[1] + 20),
                    cv2.FONT_HERSHEY_COMPLEX, 1, (0, 255, 0), thickness=2)


    cv2.imshow('Output', img)
    cv2.waitKey(0)
    cv2.destroyAllwindows()
######################################

####### From Video or Camera #######
def Camera():
    #url="http://192.168.100.51:4343/video"
    #cam=cv2.VideoCapture(url)
    cam = cv2.VideoCapture(0)

    cam.set(3, 740)
    cam.set(4, 580)

    classNames = []
    classFile = 'coco.names'

    with open(classFile, 'rt') as f:
        classNames = f.read().rstrip('\n').split('\n')

    configPath = 'ssd_mobilenet_v3_large_coco_2020_01_14.pbtxt'
    weightpath = 'frozen_inference_graph.pb'

    net = cv2.dnn.DetectionModel(configPath, weightpath)
    net.setInputSize(320 , 230)
    net.setInputScale(1.0 / 127.5)
    net.setInputMean([127.5, 127.5, 127.5])
    net.setInputSwapRB(True)

    while True:
        success, img = cam.read()
        classIds, confs, bbox = net.detect(img, confThreshold=0.5)
        print(classIds, bbox)

        if len(classIds) !=0:
            for classId, confidence, box in zip(classIds.flatten(), confs.flatten(), bbox):
                cv2.rectangle(img, box, color=(0, 255, 0), thickness=2)
                cv2.putText(img, classNames[classId-1], (box[0] + 10, box[1] + 20),
                            cv2.FONT_HERSHEY_COMPLEX, 1, (0, 255, 0), thickness=2)

        k = cv2.resize(img,(500,500))
        cv2.imshow('Output', k)
        cv2.waitKey(1)
######################################


## Call ImgFile() Function for Image Or Camera() Function for Video and Camera
#ImgFile()
Camera()
cv2.waitKey(0)
cv2.destroyAllwindows()


[1] [[  1 104 397 376]]
[1] [[  2 106 405 374]]
[1] [[  1 103 390 377]]
[1] [[  2 103 396 377]]
[ 1 63] [[  2 102 393 378]
 [ 19 333 621 147]]
[ 1 63] [[  2 101 391 379]
 [ 22 332 618 148]]
[1] [[  2 102 397 378]]
[ 1 63] [[  2 102 397 378]
 [ 20 333 620 147]]
[1] [[  2 104 395 376]]
[1] [[  2 102 396 378]]
[1] [[  2 111 403 369]]
[1] [[  3 110 396 370]]
[1] [[  2 110 414 370]]
[1] [[  2 111 404 369]]
[1] [[  2 112 414 368]]
[1] [[  2 113 404 367]]
[1] [[  3 113 398 367]]
[1] [[  2 111 407 369]]
[ 1 63] [[  3 111 396 369]
 [ 25 344 615 136]]
[1] [[  3 108 399 372]]
[1] [[  4 109 405 371]]
[1] [[  3 108 403 372]]
[1] [[  3 110 397 370]]
[1] [[  3 109 401 371]]
[ 1 63] [[  3 107 407 373]
 [ 22 337 618 143]]
[1] [[  3 108 398 372]]
[ 1 63] [[  3 108 403 372]
 [ 23 328 617 152]]
[ 1 63] [[  3 107 407 373]
 [ 21 323 619 157]]
[1] [[  3 111 402 369]]
[1] [[  1 112 394 368]]
[ 1 63] [[  1 115 394 365]
 [ 29 331 610 149]]
[1] [[  1 116 414 364]]
[1] [[  2 115 433 365]]
[1 1] [[  3 115 492 365]

KeyboardInterrupt: 

In [2]:
#باستخدام اللغه العربيه
import cv2

####### From Image #######
def ImgFile():
    img = cv2.imread('person.png')

    classNames = []
    classFile = 'coco_arabic.names'  # استخدم ملف الأسماء العربية

    with open(classFile, 'rt', encoding='utf-8') as f:  # استخدم ترميز UTF-8
        classNames = f.read().rstrip('\n').split('\n')

    configPath = 'ssd_mobilenet_v3_large_coco_2020_01_14.pbtxt'
    weightpath = 'frozen_inference_graph.pb'

    net = cv2.dnn.DetectionModel(weightpath, configPath)
    net.setInputSize(320, 230)
    net.setInputScale(1.0 / 127.5)
    net.setInputMean((127.5, 127.5, 127.5))
    net.setInputSwapRB(True)

    classIds, confs, bbox = net.detect(img, confThreshold=0.5)
    print(classIds, bbox)

    for classId, confidence, box in zip(classIds.flatten(), confs.flatten(), bbox):
        cv2.rectangle(img, box, color=(0, 255, 0), thickness=2)
        cv2.putText(img, classNames[classId - 1], (box[0] + 10, box[1] + 20),
                    cv2.FONT_HERSHEY_COMPLEX, 1, (0, 255, 0), thickness=2)

    cv2.imshow('Output', img)
    cv2.waitKey(1)
######################################

####### From Video or Camera #######
def Camera():
    cam = cv2.VideoCapture(0)

    cam.set(3, 740)
    cam.set(4, 580)

    classNames = []
    classFile = 'coco_arabic.names'  # استخدم ملف الأسماء العربية

    with open(classFile, 'rt', encoding='utf-8') as f:  # استخدم ترميز UTF-8
        classNames = f.read().rstrip('\n').split('\n')

    configPath = 'ssd_mobilenet_v3_large_coco_2020_01_14.pbtxt'
    weightpath = 'frozen_inference_graph.pb'

    net = cv2.dnn.DetectionModel(configPath, weightpath)
    net.setInputSize(320, 230)
    net.setInputScale(1.0 / 127.5)
    net.setInputMean([127.5, 127.5, 127.5])
    net.setInputSwapRB(True)

    while True:
        success, img = cam.read()
        classIds, confs, bbox = net.detect(img, confThreshold=0.5)
        print(classIds, bbox)

        if len(classIds) != 0:
            for classId, confidence, box in zip(classIds.flatten(), confs.flatten(), bbox):
                cv2.rectangle(img, box, color=(0, 255, 0), thickness=2)
                cv2.putText(img, classNames[classId - 1], (box[0] + 10, box[1] + 20),
                            cv2.FONT_HERSHEY_COMPLEX, 1, (0, 255, 0), thickness=2)

        k = cv2.resize(img, (500, 500))
        cv2.imshow('Output', k)
        cv2.waitKey(1)
######################################

## Call ImgFile() Function for Image Or Camera() Function for Video and Camera
# ImgFile()
Camera()

[1] [[112 194 490 273]]
[1] [[137 194 471 274]]
[1] [[175 192 430 277]]
[1] [[150 190 456 279]]
[1] [[158 190 438 279]]
[1] [[162 192 444 277]]
[1] [[142 191 454 277]]
[1] [[145 188 462 280]]
[1] [[147 190 465 277]]
[1] [[166 190 441 279]]
[1] [[146 190 457 278]]
[1] [[166 189 439 280]]
[1] [[146 189 456 279]]
[1] [[156 188 454 281]]
[1] [[167 191 437 278]]
[1] [[152 190 450 278]]
[1] [[150 189 456 279]]
[1] [[160 192 447 276]]
[1] [[144 190 452 278]]
[1] [[158 189 449 280]]
[1] [[149 193 454 275]]
[1] [[152 190 459 279]]
[ 1 77] [[158 193 437 275]
 [412 321  48  53]]
[ 1 77] [[149 190 458 278]
 [411 319  50  56]]
[ 1 77] [[135 191 464 276]
 [412 318  45  58]]
[ 1 77] [[133 190 468 277]
 [412 317  44  59]]
[ 1 77] [[143 189 453 278]
 [412 319  45  56]]
[ 1 77] [[133 190 461 277]
 [412 319  46  59]]
[ 1 77] [[146 188 451 279]
 [410 317  48  63]]
[1] [[149 190 460 278]]
[ 1 77] [[150 190 455 278]
 [410 319  50  58]]
[ 1 77] [[165 191 435 277]
 [412 319  46  57]]
[ 1 77] [[161 192 451 276

KeyboardInterrupt: 

In [5]:
import cv2
from PIL import Image, ImageDraw, ImageFont
import numpy as np

####### From Image #######
def ImgFile():
    img = cv2.imread('person.png')

    classNames = []
    classFile = 'coco_arabic.names'  # استخدم ملف الأسماء العربية

    with open(classFile, 'rt', encoding='utf-8') as f:  # استخدم ترميز UTF-8
        classNames = swap(f.read().split('\n'))

    configPath = 'ssd_mobilenet_v3_large_coco_2020_01_14.pbtxt'
    weightpath = 'frozen_inference_graph.pb'

    net = cv2.dnn.DetectionModel(weightpath, configPath)
    net.setInputSize(320, 230)
    net.setInputScale(1.0 / 127.5)
    net.setInputMean((127.5, 127.5, 127.5))
    net.setInputSwapRB(True)

    classIds, confs, bbox = net.detect(img, confThreshold=0.5)
    print(classIds, bbox)

    # تحويل الصورة إلى صيغة Pillow
    img_pil = Image.fromarray(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
    draw = ImageDraw.Draw(img_pil)

    for classId, confidence, box in zip(classIds.flatten(), confs.flatten(), bbox):
        cv2.rectangle(img, box, color=(0, 255, 0), thickness=2)

        # استخدام خط يدعم اللغة العربية
        font = ImageFont.truetype("arial.ttf", 20)  # تأكد من أن لديك الخط المناسب

        draw.text((box[0] + 10, box[1] + 20), classNames[classId - 1], font=font, fill=(0, 255, 0))

    # تحويل الصورة مرة أخرى إلى OpenCV
    img = cv2.cvtColor(np.array(img_pil), cv2.COLOR_RGB2BGR)

    cv2.imshow('Output', img)
    cv2.waitKey(1)

######################################

####### From Video or Camera #######
def Camera():
    cam = cv2.VideoCapture(0)

    cam.set(3, 740)
    cam.set(4, 580)

    classNames = []
    classFile = 'coco_arabic.names'  # استخدم ملف الأسماء العربية

    with open(classFile, 'rt', encoding='utf-8') as f:  # استخدم ترميز UTF-8
        classNames = f.read().rstrip('\n').split('\n')

    configPath = 'ssd_mobilenet_v3_large_coco_2020_01_14.pbtxt'
    weightpath = 'frozen_inference_graph.pb'

    net = cv2.dnn.DetectionModel(configPath, weightpath)
    net.setInputSize(320, 230)
    net.setInputScale(1.0 / 127.5)
    net.setInputMean([127.5, 127.5, 127.5])
    net.setInputSwapRB(True)

    while True:
        success, img = cam.read()
        classIds, confs, bbox = net.detect(img, confThreshold=0.5)
        print(classIds, bbox)

        # تحويل الصورة إلى صيغة Pillow
        img_pil = Image.fromarray(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
        draw = ImageDraw.Draw(img_pil)

        if len(classIds) != 0:
            for classId, confidence, box in zip(classIds.flatten(), confs.flatten(), bbox):
                cv2.rectangle(img, box, color=(0, 255, 0), thickness=2)
                reword= classNames[classId - 1]

                # استخدام خط يدعم اللغة العربية
                font = ImageFont.truetype("arial.ttf", 20)  # تأكد من أن لديك الخط المناسب

                draw.text((box[0] + 10, box[1] + 20), classNames[classId - 1][::-1], font=font, fill=(0, 255, 0))

        # تحويل الصورة مرة أخرى إلى OpenCV
        img = cv2.cvtColor(np.array(img_pil), cv2.COLOR_RGB2BGR)

        k = cv2.resize(img, (500, 500))
        cv2.imshow('Output', k)
        cv2.waitKey(1)

######################################

## Call ImgFile() Function for Image Or Camera() Function for Video and Camera
# ImgFile()
Camera()

[1 1 1 1] [[ 10 114 506 366]
 [164 115 467 365]
 [ 53  28 579 403]
 [  0 100 266 380]]
[1 1 1 1] [[ 16 114 444 366]
 [159 115 475 365]
 [ 65  31 569 400]
 [  0 101 259 379]]
[1 1 1 1] [[ 22 112 384 368]
 [159 115 476 365]
 [ 73  33 560 401]
 [  1 102 252 378]]
[1 1 1 1] [[ 18 109 328 371]
 [208 114 428 366]
 [ 74  33 560 403]
 [  0  57 253 405]]
[1 1 1 1] [[ 18 111 352 369]
 [186 115 450 365]
 [ 76  34 558 402]
 [  0  61 253 404]]
[1 1 1 1] [[ 19 111 317 369]
 [187 115 449 365]
 [ 85  34 547 404]
 [  0  55 253 407]]
[1 1 1 1] [[ 18 113 409 367]
 [196 114 439 366]
 [ 71  30 565 403]
 [  0 103 256 377]]
[1 1 1 1] [[ 15 112 396 368]
 [226 113 409 367]
 [  0 104 251 376]
 [ 76  30 558 405]]
[1 1 1] [[ 30 115 596 365]
 [  0 104 259 376]
 [306 118 334 362]]
[1 1 1 1] [[ 15 115 439 365]
 [142 116 494 364]
 [ 71  32 565 399]
 [  0 103 260 377]]
[1 1 1 1] [[ 17 115 445 365]
 [151 116 484 364]
 [ 64  29 570 402]
 [  0 101 260 379]]
[1 1 1 1] [[ 16 111 413 369]
 [212 116 421 364]
 [ 66  33 567 40

KeyboardInterrupt: 

In [46]:
import cv2
import numpy as np
from PIL import Image, ImageDraw, ImageFont
import arabic_reshaper
from bidi.algorithm import get_display

####### From Image #######
def ImgFile():
    img = cv2.imread('person.png')

    classNames = []
    classFile = 'coco_arabic.names'  # تأكد من أن الملف يحتوي على الأسماء باللغة العربية

    with open(classFile, 'rt', encoding='utf-8') as f:
        classNames = f.read().rstrip('\n').split('\n')

    configPath = 'ssd_mobilenet_v3_large_coco_2020_01_14.pbtxt'
    weightpath = 'frozen_inference_graph.pb'

    net = cv2.dnn.DetectionModel(weightpath, configPath)
    net.setInputSize(320, 230)
    net.setInputScale(1.0 / 127.5)
    net.setInputMean((127.5, 127.5, 127.5))
    net.setInputSwapRB(True)

    classIds, confs, bbox = net.detect(img, confThreshold=0.5)
    print(classIds, bbox)

    # تحويل الصورة إلى صيغة Pillow
    img_pil = Image.fromarray(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
    draw = ImageDraw.Draw(img_pil)

    # استخدام خط يدعم اللغة العربية
    font_path = "arial.ttf"  # تأكد من أن لديك الخط المناسب
    font_size = 20
    font = ImageFont.truetype(font_path, font_size)

    for classId, confidence, box in zip(classIds.flatten(), confs.flatten(), bbox):
        # رسم المربع على الصورة
        cv2.rectangle(img, box, color=(0, 255, 0), thickness=2)
        
        # رسم النص على الصورة
        text = classNames[classId - 1][::-1]
        cv2.putText(img,text,(box[0] + 10, box[1] + 10),cv2.FONT_HERSHEY_COMPLEX,1,(0,0,255),thickness=2)

    # تحويل الصورة مرة أخرى إلى OpenCV
    img = cv2.cvtColor(np.array(img_pil), cv2.COLOR_RGB2BGR)

    cv2.imshow('Output', img)
    cv2.waitKey(1)
######################################

####### From Video or Camera #######
def Camera():
    cam = cv2.VideoCapture(0)

    cam.set(3, 740)
    cam.set(4, 580)

    classNames = []
    classFile = 'coco_arabic.names'  # تأكد من أن الملف يحتوي على الأسماء باللغة العربية

    with open(classFile, 'rt', encoding='utf-8') as f:
        classNames = f.read().rstrip('\n').split('\n')

    configPath = 'ssd_mobilenet_v3_large_coco_2020_01_14.pbtxt'
    weightpath = 'frozen_inference_graph.pb'

    net = cv2.dnn.DetectionModel(configPath, weightpath)
    net.setInputSize(320, 230)
    net.setInputScale(1.0 / 127.5)
    net.setInputMean([127.5, 127.5, 127.5])
    net.setInputSwapRB(True)

    while True:
        success, img = cam.read()
        classIds, confs, bbox = net.detect(img, confThreshold=0.5)
        print(classIds, bbox)

        # تحويل الصورة إلى صيغة Pillow
        img_pil = Image.fromarray(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
        draw = ImageDraw.Draw(img_pil)

        # استخدام خط يدعم اللغة العربية
        font_path = "ARIAL.TTF"  # تأكد من أن لديك الخط المناسب
        font_size = 20
        font = ImageFont.truetype(font_path, font_size)

        if len(classIds) != 0:
            for classId, confidence, box in zip(classIds.flatten(), confs.flatten(), bbox):
                
                img = cv2.cvtColor(np.array(img_pil), cv2.COLOR_RGB2BGR)
                # رسم المربع على الصورة
                cv2.rectangle(img, box, color=(0, 255, 0), thickness=2)

                text = classNames[classId - 1][::-1]
                
                
                # رسم النص على الصورة
                draw.text((box[0] + 10, box[1] + 10), text, font=font, fill=(255, 255, 255))

        # تحويل الصورة مرة أخرى إلى OpenCV

        k = cv2.resize(img, (500, 500))
        cv2.imshow('Output', k)
        cv2.waitKey(1)

######################################

## Call ImgFile() Function for Image Or Camera() Function for Video and Camera
# ImgFile()
Camera()

[63] [[  1 351 634 129]]
[63] [[  1 351 631 129]]
[63] [[  0 352 631 128]]
[63] [[  0 351 635 129]]
[63] [[  0 352 639 128]]
[63] [[  0 350 636 130]]
[63] [[  2 351 628 129]]
[63] [[  3 352 627 128]]
[63] [[  3 349 628 131]]
[63] [[  1 344 632 136]]
[63] [[  1 349 631 131]]
[63] [[  2 348 633 132]]
[63] [[  4 347 626 133]]
[63] [[  5 339 626 141]]
[63] [[ 10 339 614 141]]
[63] [[  8 337 621 143]]
[63] [[  6 341 618 139]]
[63] [[  9 341 612 139]]
[63] [[  6 334 616 146]]
[63] [[  9 336 615 144]]
[63] [[ 11 340 609 140]]
[63] [[ 11 342 613 138]]
[63] [[  7 341 612 139]]
[63] [[  7 339 617 141]]
[63] [[  7 340 619 140]]
[63] [[  8 337 616 143]]
[63] [[  5 340 624 140]]
[63] [[  9 341 615 139]]
[63] [[  9 341 617 139]]
[63] [[  7 338 621 142]]
[63] [[  6 338 623 142]]
[63] [[  7 339 622 141]]
[63] [[  4 337 630 143]]
[63] [[  7 340 621 140]]
[63] [[  4 340 625 140]]
[63] [[  7 341 624 139]]
[63] [[  8 340 620 140]]
[63] [[  8 343 620 137]]
[63] [[  7 342 624 138]]
[63] [[  7 339 625 141]]


KeyboardInterrupt: 

In [40]:
print(dir(cv2.FONT_HERSHEY_COMPLEX))
print(help(cv2.FONT_HERSHEY_COMPLEX))

['__abs__', '__add__', '__and__', '__bool__', '__ceil__', '__class__', '__delattr__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floor__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__le__', '__lshift__', '__lt__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rrshift__', '__rshift__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__trunc__', '__xor__', 'as_integer_ratio', 'bit_count', 'bit_length', 'conjugate', 'denominator', 'from_bytes', 'imag', 'numerator', 'real', 'to_bytes']
Help on int object:

class int(object)
 |  int([x]) 

In [64]:
##جاهز للتعرف باللغه العربيه
import cv2
import numpy as np
from PIL import Image, ImageDraw, ImageFont
import arabic_reshaper
from bidi.algorithm import get_display

####### From Image #######
def ImgFile():
    img = cv2.imread('person.png')

    classNames = []
    classFile = 'coco_arabic.names'  # تأكد من أن الملف يحتوي على الأسماء باللغة العربية

    with open(classFile, 'rt', encoding='utf-8') as f:
        classNames = f.read().rstrip('\n').split('\n')

    configPath = 'ssd_mobilenet_v3_large_coco_2020_01_14.pbtxt'
    weightpath = 'frozen_inference_graph.pb'

    net = cv2.dnn.DetectionModel(weightpath, configPath)
    net.setInputSize(320, 230)
    net.setInputScale(1.0 / 127.5)
    net.setInputMean((127.5, 127.5, 127.5))
    net.setInputSwapRB(True)

    classIds, confs, bbox = net.detect(img, confThreshold=0.1)
    print(classIds, bbox)

    # تحويل الصورة إلى صيغة Pillow
    img_pil = Image.fromarray(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
    draw = ImageDraw.Draw(img_pil)

    # استخدام خط يدعم اللغة العربية
    font_path = "arial.ttf"  # تأكد من أن لديك الخط المناسب
    font_size = 20
    font = ImageFont.truetype(font_path, font_size)

    for classId, confidence, box in zip(classIds.flatten(), confs.flatten(), bbox):
        # رسم المربع على الصورة
        cv2.rectangle(img, box, color=(0, 255, 0), thickness=2)

        # تجهيز النص باللغة العربية
        text = classNames[classId - 1]
        reshaped_text = arabic_reshaper.reshape(text)
        bidi_text = get_display(reshaped_text)

        # رسم النص على الصورة
        draw.text((box[0] + 10, box[1] + 10), bidi_text, font=font, fill=(255, 255, 255))

    # تحويل الصورة مرة أخرى إلى OpenCV
    img = cv2.cvtColor(np.array(img_pil), cv2.COLOR_RGB2BGR)

    cv2.imshow('Output', img)
    cv2.waitKey(1)

######################################

####### From Video or Camera #######
def Camera():
    #url="http://192.168.100.51:4343/video"
    #cam=cv2.VideoCapture(url)
    cam = cv2.VideoCapture(0)

    cam.set(3, 740)
    cam.set(4, 580)

    classNames = []
    classFile = 'coco_arabic.names'  # تأكد من أن الملف يحتوي على الأسماء باللغة العربية

    with open(classFile, 'rt', encoding='utf-8') as f:
        classNames = f.read().rstrip('\n').split('\n')

    configPath = 'ssd_mobilenet_v3_large_coco_2020_01_14.pbtxt'
    weightpath = 'frozen_inference_graph.pb'

    net = cv2.dnn.DetectionModel(configPath, weightpath)
    net.setInputSize(320, 230)
    net.setInputScale(1.0 / 127.5)
    net.setInputMean([127.5, 127.5, 127.5])
    net.setInputSwapRB(True)

    while True:
        success, img = cam.read()
        classIds, confs, bbox = net.detect(img, confThreshold=0.5)
        print(classIds, bbox)

        
        # استخدام خط يدعم اللغة العربية
        font_path = "arial.ttf"  # تأكد من أن لديك الخط المناسب
        font_size = 20
        font = ImageFont.truetype(font_path, font_size)

        if len(classIds) != 0:
            for classId, confidence, box in zip(classIds.flatten(), confs.flatten(), bbox):
                # رسم المربع على الصورة
                cv2.rectangle(img, box, color=(0, 255, 0), thickness=2)
                # تحويل الصورة إلى صيغة Pillow
                img_pil = Image.fromarray(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
                draw = ImageDraw.Draw(img_pil)

                # تجهيز النص باللغة العربية
                text = classNames[classId - 1]
                reshaped_text = arabic_reshaper.reshape(text)
                bidi_text = get_display(reshaped_text)

                # رسم النص على الصورة
                draw.text((box[0] + 10, box[1] + 10), bidi_text, font=font, fill=(255, 255, 255))
            # تحويل الصورة مرة أخرى إلى OpenCV
            img = cv2.cvtColor(np.array(img_pil), cv2.COLOR_RGB2BGR)
                

        k = cv2.resize(img, (1000, 700))
        cv2.imshow('Output', k)
        cv2.waitKey(1)

######################################

## Call ImgFile() Function for Image Or Camera() Function for Video and Camera
# ImgFile()
Camera()

[1] [[  4 148 450 332]]
[ 1 63] [[  4 148 447 332]
 [ 25 339 615 141]]
[1] [[  8 149 423 331]]
[1] [[  7 148 436 332]]
[ 1 63] [[  8 146 435 334]
 [ 23 344 617 136]]
[1] [[  3 143 452 337]]
[ 1 63] [[  3 142 455 338]
 [ 22 341 618 139]]
[ 1 63] [[ 18 149 415 331]
 [ 33 341 607 139]]
[ 1 63] [[ 15 148 422 332]
 [ 30 341 610 139]]
[ 1 63] [[  9 148 434 332]
 [ 26 339 614 141]]
[ 1 63  1] [[  5 150 471 330]
 [ 23 342 617 138]
 [  0  63 640 362]]
[1 1] [[  7 150 482 330]
 [  0  64 640 361]]
[ 1  1 63] [[  9 149 510 331]
 [  0  66 640 360]
 [ 25 347 615 133]]
[ 1 63] [[  6 152 454 328]
 [ 27 342 613 138]]
[1 1] [[  6 153 483 327]
 [  0  65 640 362]]
[1] [[  6 153 447 327]]
[ 1  1 63] [[ 12 152 494 328]
 [  0  65 640 361]
 [ 21 340 619 140]]
[ 1 63] [[ 13 153 454 327]
 [ 22 341 618 139]]
[1 1] [[  9 154 487 326]
 [  0  65 640 361]]
[ 1 63] [[  6 151 474 329]
 [ 22 339 618 141]]
[1 1] [[  7 154 495 326]
 [  0  65 640 361]]
[ 1  1 63] [[  8 152 516 328]
 [  0  65 640 361]
 [ 19 345 621 135]]
[

KeyboardInterrupt: 

In [ ]:
import cv2
import numpy as np

####### From Image #######
def ImgFile():
    img = cv2.imread('person.png')

    classNames = []
    classFile = 'coco_arabic.names'

    with open(classFile, 'rt', encoding='utf-8') as f:
        classNames = f.read().rstrip('\n').split('\n')

    configPath = 'ssd_mobilenet_v3_large_coco_2020_01_14.pbtxt'
    weightpath = 'frozen_inference_graph.pb'

    net = cv2.dnn.DetectionModel(weightpath, configPath)
    net.setInputSize(320, 230)
    net.setInputScale(1.0 / 127.5)
    net.setInputMean((127.5, 127.5, 127.5))
    net.setInputSwapRB(True)

    classIds, confs, bbox = net.detect(img, confThreshold=0.5)
    print(classIds, bbox)

    for classId, confidence, box in zip(classIds.flatten(), confs.flatten(), bbox):
        # رسم المربع على الصورة
        cv2.rectangle(img, box, color=(0, 255, 0), thickness=2)

        # رسم النص على الصورة باستخدام OpenCV
        text = classNames[classId - 1]
        # تغيير موضع النص إذا كان مقلوباً
        cv2.putText(img, text, (box[0] + 10, box[1] + 30),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 0), 2, cv2.LINE_AA)

    cv2.imshow('Output', img)
    cv2.waitKey(1)

######################################

####### From Video or Camera #######
def Camera():
    cam = cv2.VideoCapture(0)

    cam.set(3, 740)
    cam.set(4, 580)

    classNames = []
    classFile = 'coco_arabic.names'

    with open(classFile, 'rt', encoding='utf-8') as f:
        classNames = f.read().rstrip('\n').split('\n')

    configPath = 'ssd_mobilenet_v3_large_coco_2020_01_14.pbtxt'
    weightpath = 'frozen_inference_graph.pb'

    net = cv2.dnn.DetectionModel(configPath, weightpath)
    net.setInputSize(320, 230)
    net.setInputScale(1.0 / 127.5)
    net.setInputMean([127.5, 127.5, 127.5])
    net.setInputSwapRB(True)

    while True:
        success, img = cam.read()
        classIds, confs, bbox = net.detect(img, confThreshold=0.5)
        print(classIds, bbox)

        if len(classIds) != 0:
            for classId, confidence, box in zip(classIds.flatten(), confs.flatten(), bbox):
                # رسم المربع على الصورة
                cv2.rectangle(img, box, color=(0, 255, 0), thickness=2)

                # رسم النص على الصورة باستخدام OpenCV
                text = classNames[classId - 1]
                # تغيير موضع النص إذا كان مقلوباً
                #cv2.putText(img, text, (box[0] + 10, box[1] + 30),
                 #           cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 0), 2, cv2.LINE_AA)

        k = cv2.resize(img, (500, 500))
        cv2.imshow('Output', k)
        cv2.waitKey(1)

######################################

## Call ImgFile() Function for Image Or Camera() Function for Video and Camera
# ImgFile()
Camera()

[ 1 77 77 77] [[ 89 165 452 303]
 [370 301  85 158]
 [368 332  68  64]
 [380 312  47  53]]
[ 1 77] [[ 83 164 464 303]
 [367 312  88 148]]
[ 1 77 77] [[ 85 166 467 301]
 [367 305  84 153]
 [368 331  69  66]]
[ 1 77 77] [[ 74 166 478 301]
 [367 312  88 151]
 [367 335  72  64]]
[ 1 77 77 77] [[ 73 167 476 300]
 [368 301  87 167]
 [366 332  73  68]
 [379 312  50  50]]
[ 1 77 77] [[ 80 166 469 302]
 [368 304  87 155]
 [367 332  76  69]]
[ 1 77 77] [[ 80 165 467 302]
 [368 306  86 155]
 [368 334  73  63]]
[ 1 77 77] [[ 74 165 474 301]
 [367 296  86 171]
 [378 310  52  53]]
[ 1 77] [[ 78 165 476 302]
 [367 305  89 156]]
[ 1 77] [[ 82 167 464 300]
 [367 303  91 161]]
[ 1 77 77] [[ 81 165 468 301]
 [368 304  91 162]
 [367 332  73  65]]
[ 1 77 77] [[ 78 165 476 302]
 [365 301  88 162]
 [377 310  53  55]]
[ 1 77] [[ 86 166 462 300]
 [368 309  82 157]]
[ 1 77 77] [[ 83 166 467 301]
 [366 315  85 152]
 [367 335  71  59]]
[ 1 77 77] [[ 85 167 463 301]
 [365 311  89 154]
 [366 336  74  59]]
[ 1 77 77

KeyboardInterrupt: 